hydra:
  run:
    dir: ../results/${experiment.name}

mlflow:
  track: True
  tracking_uri: ../results/mlflow # http://127.0.0.1:5000

experiment:
  name: 'name'
  run_name:
  folder: ${experiment.name}
  experiment_dir: ../results/${experiment.name}

  device: 'cpu'
  verbose: True
  seed: 0

defaults:
  - env: env
  - agent: ppo
  - _self_

# TODO: think about refactoring the following params, so both env and agent can use without duplication ?
env:
  experiment_folder: ${experiment.experiment_dir}
  device: ${experiment.device}
  verbose: ${experiment.verbose}
  seed: ${experiment.seed}

agent:
  experiment_folder: ${experiment.experiment_dir}
  experiment_dir: ${experiment.experiment_dir}
  device: ${experiment.device}
  verbose: ${experiment.verbose}
  seed: ${experiment.seed}
  control_space_type: 'exponential'

# python run_RL_agent.py experiment.name=test33 experiment.device=cpu agent=ppo agent.debug=True hydra/job_logging=disabled

